### ISSUE TITLE
Small strokes

### ISSUE THREAD

**Issue by nycoliver** [chanind/hanzi-writer#10]
Hi, thanks for the great library! Small issue -- small strokes take up the whole screen. 丶for instance. Can't think of a simple fix and wondering if you have any suggestions.

**Comment by chanind** [comment]
Hey, sorry for the comically slow response! I just updated the datasource for Hanzi Writer to use https://github.com/skishore/makemeahanzi instead of ZDT. I think the new data source handles this better. Give it a try and let me know what you think!

**Comment by chanind** [comment]
Closing for now, feel free to repoen if this is still an issue.

**Comment by nycoliver** [comment]
Should be fine, I also switched to makemeahanzi for my project and it's great!
