### ISSUE TITLE
关于字体授权问题

### ISSUE THREAD

**Issue by weikeyan** [chanind/hanzi-writer#100]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/7971897/50534339-31bc9600-0b76-11e9-9f84-a4b4d9f4fba0.png">
请问您用到的是哪一个字体呢？Arphic PL KaitiM GB and Arphic PL UKai.  这两个字体似乎是不能商用的，想跟您确定下您用的是哪一种？

**Comment by chanind** [comment]
I'm not sure - Hanzi Writer directly uses the data from [MakeMeAHanzi](https://github.com/skishore/makemeahanzi), so you'll have to ask in that repo.

**Comment by liangqi** [comment]
https://github.com/skishore/makemeahanzi/blob/master/README.md

> graphics.txt and svgs.tar.gz are derived from two free fonts: Arphic PL KaitiM GB and Arphic PL UKai.
> 
> This project would not have been possible without the generosity of Arphic Technology, a Taiwanese font forge that released their work under a permissive license in 1999.

https://packages.ubuntu.com/xenial/all/fonts-arphic-gkai00mp/filelist

https://packages.ubuntu.com/xenial/all/fonts-arphic-ukai/filelist

https://www.freedesktop.org/wiki/Arphic_Public_License/
