### ISSUE TITLE
HanziWriter 能设置html百分百宽高么

### ISSUE THREAD

**Issue by weikeyan** [chanind/hanzi-writer#103]
HanziWriter 能设置html百分百宽高么

**Comment by chanind** [comment]
You want to be able to set HanziWriter to render at 100% of the size of the screen? There's not a built-in way to do that, but you could probably use javascript to measure the size of the screen and then use that result to set the width/height in HanziWriter. Is that what you're asking?

For example, I haven't tested this but I think it would work:
```
var size  = Math.min(window.innerHeight, window.innerWidth);
HanziWriter.create('target-div', '我', {
    width: size,
    height: size,
    padding: 0,
});
```
