### ISSUE TITLE
Why safari browser does not display properly

### ISSUE THREAD

**Issue by 1248664852** [chanind/hanzi-writer#104]
Strokes show special thick？google is normal

**Comment by chanind** [comment]
I'm having trouble reproducing this in Safari. Could you take a screenshot to show what you mean?

**Comment by 1248664852** [comment]
![WechatIMG5686](https://user-images.githubusercontent.com/31099619/55777701-40024280-5ad3-11e9-9d5a-f5283afee611.jpeg)
thank you

**Comment by chanind** [comment]
whoa that's super messed up. It works for me in Safari, so I'm not sure what the issue is. Which version of safari are you using, and on which device? Do you have it running on a demo page somewhere I can take a look at?

**Comment by 1248664852** [comment]
http://www.wehanyu.com/letter/731
You can refer to this text

**Comment by bryangingechen** [comment]
See also this thread, with a potential solution:

https://talk.observablehq.com/t/hanzi-writer-renders-incorrectly-inside-an-observable-notebook-on-a-mobile-browser/1898/2

**Comment by chanind** [comment]
This should be fixed now in v1.3.1. Let me know if you still see the issue!

**Comment by 1248664852** [comment]
Thank you so much，it solved


------------------ 原始邮件 ------------------
发件人: "chanind"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 晚上8:48
收件人: "chanind/hanzi-writer"<hanzi-writer@noreply.github.com>;
抄送: "Fun"<1248664852@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [chanind/hanzi-writer] Why safari browser does not displayproperly (#104)




This should be fixed now in v1.3.1. Let me know if you still see the issue!
