### ISSUE TITLE
求个小程序能使用的版本

### ISSUE THREAD

**Issue by zmqcherish** [chanind/hanzi-writer#108]
微信小程序无法使用很多原生的语句，比如document.getElementById，
求一个小程序能用的

**Comment by chanind** [comment]
I don't know much about mini-program development, but would love to make Hanzi Writer compatible with mini-programs! What needs to change to make it usable with Mini-programs? Is it only `document.getElementById` that's not supported? What should `document.getElementById` be replaced with?

**Comment by zmqcherish** [comment]
many javascript raw functions can not use, and can do something with dom. I don't know how to describe the all limit.
thanks you anyway

**Comment by RocketV2** [comment]
Many people use weChat in China,  and the mini-program is a useful app in weChat. so I hope the hanzi-writer can support it.  

developer document:
    https://developers.weixin.qq.com/miniprogram/en/dev/quickstart/basic/getting-started.html#install-development-tools

**Comment by chanind** [comment]
Thanks for the docs link! I'll take a look and try to get a wechat-compatible version working this week

**Comment by hqzh** [comment]
@chanind this program is a personal interest?

**Comment by chanind** [comment]
Sorry, I don't really understand the question. It's not a company, it's just a free open-source project. If you want to improve the code you can contribute a pull request as well!

**Comment by chanind** [comment]
It looks like Wechat miniprograms support [canvas](https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html), but I can't find anything about working with SVG. I'll work on getting canvas rendering support completed and then try porting that over to wechat.

**Comment by chanind** [comment]
I just published a miniprogram custom component with the name `hanzi-writer-miniprogram`. Let me know if it works, or if there's problems with it! The repo is here: https://github.com/chanind/hanzi-writer-miniprogram. I'll improve the docs over the next few days, and publish a 1.0.0 version if it seems like the plugin works.

**Comment by chanind** [comment]
Closing this because a miniprogram plugin for Hanzi Writer now exists at: https://github.com/chanind/hanzi-writer-miniprogram
