### ISSUE TITLE
feature: Show radical color

### ISSUE THREAD

**Issue by fzzylogic** [chanind/hanzi-writer#11]
This is a fantastic project! Thanks so much for sharing this.

ZDT somehow used the data to show radical in red, when present. So this is a feature request..

Looking at the stroke file, ZDT may have identified the radical from the prefix information.
For the character 成 (the example on the main zdt page), the stroke data file prefixes are: 

1PR
4PO
1NO
3NO
6PO
2NR
7PR
4PR
2PR

I guess the numbers are direction of stroke. Maybe the second character is related to whether or not the final part of a complete stroke is being drawn (P seems to indicate final, whereas N means there are still additional parts remaining to the stroke). But for radical colorizing purposes it looks like the R of the third character stands for Radical.. (With O meaning non-radical) If that is really so, it shouldn't be too hard to also imitate ZDT's radical coloring feature. In the above example, the reason the first stroke contains an R is that the first stroke of the radical (戈) has been joined with the second stroke of the 方 preceeding it. So since they did not record two separate strokes, the entire first stroke will be red. Checked this theory against 你 as well and it works there too.

**Comment by chanind** [comment]
This definitely should be possible - thanks for opening the issue! I don't have time in the short term to add this feature but if you or someone else wants to do it and open a PR go for it!
