### ISSUE TITLE
笔画顺序问题

### ISSUE THREAD

**Issue by hongxxh** [chanind/hanzi-writer#110]
技术上我没细看，暂且不评，但是很多笔画顺序，比如必、右，显然是有问题。

**Comment by Tamshen** [comment]
我在百度汉语上看“必”、“右” 好像是正确的？[链接](https://hanyu.baidu.com/s?wd=右&ptype=zici&tn=sug_click)

**Comment by hongxxh** [comment]
其实问题不大，毕竟大家都是写错的...你可以看看这个，因为汉字有一个发展的历史，所以有些笔画顺序沿袭了古法。 https://www.zhihu.com/question/31812137
这个技术上确实很酷👍

**Comment by Juphy** [comment]
正确的笔顺，看看古人的行书、草书就知道了，错误的笔顺在楷书的书写上可能没什么，但是行、草书必然有问题

**Comment by chanind** [comment]
closing since it seems like this is not a big problem
