### ISSUE TITLE
a hanzi-writer page.

### ISSUE THREAD

**Issue by Koooooo-7** [chanind/hanzi-writer#111]
Hi ! :smiley: 
I think it is really a useful  project  ,but it  is not a  friendly tool  to be used by users. :joy_cat: 
 To make it  easily, I  deploed a simple  [hanzi-writer page](https://koooooo-7.github.io/HanziWriterPage/) ， which  can suits  mobile telephone.   
I have no more details  about the **MIT license** , so I wanna make sure
would u mind what I had done ? or  I haven't the right，either .
 thx .

**Comment by chanind** [comment]
This is great! The MIT license is [here](https://opensource.org/licenses/MIT). The data is under the Arphic Public License [here](https://raw.githubusercontent.com/chanind/hanzi-writer-data/master/ARPHICPL.TXT). I'm not a lawyer, but the page you made looks great to me! Nice job!

**Comment by Koooooo-7** [comment]
@chanind  thx for your encouragement. :wink: 
I'll try to  know the requirements of the  license  ...(I' m not a lawyer ,too. :rofl: )
