### ISSUE TITLE
When I started painting Chinese characters, I was given an error.

### ISSUE THREAD

**Issue by 1248664852** [chanind/hanzi-writer#119]
Hello!
My project is upgraded to angular8.0.0 and then this problem occurs.

![image](https://user-images.githubusercontent.com/31099619/59257571-c91b2e80-8c68-11e9-89e3-5af104117265.png)

**Comment by chanind** [comment]
I'm extremely sorry, this seems like it was a regression in 1.4.2. If you upgrade to 2.0.1 it should be fixed now. Thank you so much for finding and reporting this!!

**Comment by 1248664852** [comment]
thank you  old tie!!!


------------------ 原始邮件 ------------------
发件人: "chanind"<notifications@github.com>;
发送时间: 2019年6月11日(星期二) 晚上6:42
收件人: "chanind/hanzi-writer"<hanzi-writer@noreply.github.com>;
抄送: "Fun"<1248664852@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [chanind/hanzi-writer] When I started painting Chinesecharacters, I was given an error. (#119)




I'm extremely sorry, this seems like it was a regression in 1.4.2. If you upgrade to 2.0.1 it should be fixed now. Thank you so much for finding and reporting this!!
