### ISSUE TITLE
setCharacter adds a character instead of replacing it

### ISSUE THREAD

**Issue by josephjohnston** [chanind/hanzi-writer#129]
Below is a post by Mikurox from issue 55. I have the same bug and I'm wondering if I'm misunderstanding how setCharacter should work. Documentation say 'Replace the currently drawn character with a new one', but instead it adds a new and disfigured character like his picture shows. 

Hi guys, I totally agree with you on the above, I was going to raise the following bug when I saw this one

- create a new HanziWriter() object to initialise it (it's still hidden so not used yet)
`this.writer = new HanziWriter(characterDiv, character, {
			width: imgWidth,
			height: imgHeight,
			padding: 5,
			showOutline: true,
			drawingWidth: 22, // thickness of the drawing
			delayBetweenStrokes: 400, // milliseconds
			showCharacter: false,
			highlightOnComplete: false
		});`
- then later call the setCharacter method in order to really set the character we want you want
`this.writer.setCharacter(character);`

It creates 2 'g' elements in the 'svg' one, with a bad overriding etc. as a consequence.

![screen shot 2018-09-18 at 09 57 23](https://user-images.githubusercontent.com/26358541/45673277-8c336880-bb2a-11e8-8bde-90689de8ef80.png)

It may not have been the "way to use it" but in my case I would like to initialise everything before hand before even knowing which character I want to use.

So I'm looking forward for a fix as described above, or at least a fix on the new + set -> error

_Originally posted by @Mikurox in https://github.com/chanind/hanzi-writer/issues/55#issuecomment-422296468_

**Comment by chanind** [comment]
That definitely looks like a bug if that's still happening. Calling setCharacter should delete the previous `g` element, but it looks like that's not working for some reason - will dig into this further. The `new HanziWriter(div, char, opts)` style is deprecated though, so you may want to switch to using either `HanziWriter.create` or `writer = new HanziWriter(div, opts); writer.setCharacter(char)`.

**Comment by josephjohnston** [comment]
Yes, I'm using `HanziWriter.create`. Thanks for your attention to this

**Comment by chanind** [comment]
I can reproduce this issue if `setCharacter` is called before the previous character has finished loading. Working on a fix now

**Comment by chanind** [comment]
This should be fixed now in 2.0.3. Thanks for pointing this out!

If you want to initialize everything before you know what character to render, it's best to set up the writer with:
```js
var writer = new HanziWriter(div, opts);
```
Then, when you know what you want to draw, call: `writer.setCharacter(char)`.  This will be more efficient since you won't need to load and render a character that gets thrown away.
