### ISSUE TITLE
trouble importing node module

### ISSUE THREAD

**Issue by LeeMeyer** [chanind/hanzi-writer#13]
sorry for the possible noob question - HanziWriter works great for me when I include it using a script tag. but when I try the following in my node.js project

```
import {  HanziWriter }  from 'hanzi-writer';


var hanziWriter = new HanziWriter('target-div', '我', {
        width: 300,
        height: 300,
        showOutline: true,
        showCharacter: false,
        strokeAnimationDuration: 1000,
        delayBetweenStrokes: 0,
        showHintAfterMisses: 1
    });

```

i get the javascript error

"_hanziWriter.HanziWriter is not a constructor"

I am not sure what I am doing wrong?

**Comment by chanind** [comment]
I think it should work if you import it as `import HanziWriter  from 'hanzi-writer';`. Let me know if that's not the case and I'll dig into it more

**Comment by LeeMeyer** [comment]
thank you for the quick reply! 

after removing the curly braces I do seem to hit the constructor but get an error in hanzi-writer-lib.js:3631 Uncaught (in promise) TypeError: Cannot read property 'numberOfItems' of undefined(…) in Chrome.

It looks like this is because SVG.parser.path.pathSegList is undefined. :(

**Comment by chanind** [comment]
Oops, it seems I forgot to update the npm module with the most recent version of the repo. Just pushed to npm now. Really sorry about that! If you use 0.1.9 it should work.

**Comment by LeeMeyer** [comment]
thank you so much! no need to apologize - I feel lucky this project exists at all. :)
