### ISSUE TITLE
Touch screen

### ISSUE THREAD

**Issue by TowelSniffer** [chanind/hanzi-writer#135]
I am using this with flashcards on Anki however I find it does not work with touch screen devices.

**Comment by chanind** [comment]
Is there an anki plugin you're using? How can I reproduce the issue?

**Comment by TowelSniffer** [comment]
Hi thanks for the response, Looking into it, it seems to be a problem with Anki. I find this does not work when using Anki versions after 2.5 with my Wacom tablet however it works for the latest version if using Anki alternate (Which I am currently using on Linux). The cards don't work on ankidroid either and I had assumed the issues were related but after some testing, I think they aren't. 

I was using this for my cards:

var writer = HanziWriter.create('kanji-holder', '{{Kanji}}', {
  width: 150,
  height: 150,
  strokeColor: '#DDD',
  padding: 0,
showCharacter: false,
showOutline: false,
  showHintAfterMisses:3,
drawingWidth:50,
  charDataLoader: (char, onLoad, onError) => {

    fetch('_{{Kanji}}.json')

      .then(res => res.json())

      .then(onLoad)

      .catch(onError);

  }

});
writer.quiz();

When it wouldn't let me write, I thought it was a touch screen issue, but I tried to animate the character in a similar way and it wouldn't load. For some reason, ankidroid does not want to fetch my characters from the media folder. Sorry for wasting your time.
