### ISSUE TITLE
原生客户端上的使用

### ISSUE THREAD

**Issue by SeongBrave** [chanind/hanzi-writer#138]
能否提供一种方式在iOS或者Android客户端上的使用呢？或者是通过js能否在后端生成img或者gif的Api呢

**Comment by chanind** [comment]
If you want to use it on iOS or Android you can use a Webview. There's not an easy way I know of to generate a GIF or SVG image via the api, but if you find a way to do that it would be a cool addition! There's also animation images of the characters generated by the original makemeahanzi project you can use here: https://github.com/skishore/makemeahanzi/tree/master/svgs

**Comment by SeongBrave** [comment]
非常感谢~

**Comment by chanind** [comment]
no problem! Closing this issue for now
