### ISSUE TITLE
Consider adding highlight method to quiz

### ISSUE THREAD

**Issue by killia15** [chanind/hanzi-writer#145]
Awesome project!

I really like the highlight feature on the quiz it gives the user a hint after so many incorrect attempts. For my use case, I'm looking to use the quiz as more of a learning tool where it highlights each stroke and has the user trace it.

I tried using the animateStroke method but there's no way to really un-animate it to give the user an opportunity to trace it. The highlightStroke method in quiz actions isn't exposed so I can't directly use that.

What are your thoughts on adding a public method to highlight the current stroke in a quiz? I think that it'd be easy to add. I'd be happy to add it myself if that's something that you would be interested in. If not, no big deal, I can fork it - but I'd rather not if not necessary.

**Comment by chanind** [comment]
That sounds like a reasonable feature to add, should just be a few lines of code too. I'l work on getting PR up soon!

**Comment by killia15** [comment]
Awesome, let me know if there's anything that I can do to help.
