### ISSUE TITLE
Update data license information

### ISSUE THREAD

**Issue by skishore** [chanind/hanzi-writer#15]
Hey! I maintain [Make Me a Hanzi](https://github.com/skishore/makemeahanzi), and I discovered your project through someone who uses your library to make use of that data. Just a quick note: since that data is licensed under the original Arphic Public License, it must be distributed with that license and with a note of the copyright.

[The license files themselves are here.](https://github.com/skishore/makemeahanzi/tree/master/APL) I've  been noting it as two items in other projects ([https://www.skishore.me/inkstone/](https://www.skishore.me/inkstone/)) that use the data, since the data includes both the font and the work I did on top of it:

Arphic PL KaitiM GB and UKai
Copyright 1999 Arphic Technology Co., Ltd.; licensed under the Arphic Public License
http://www.arphic.com.tw/en/home/index

Make Me a Hanzi
Copyright 1999 Arphic Technology Co., Ltd., copyright 2016 Shaunak Kishore; licensed under the Arphic Public License
https://github.com/skishore/makemeahanzi

Great work on this project! It really is a useful library for anyone building a Chinese learning website.

**Comment by chanind** [comment]
Sorry about that! I made a PR here adding the APL and copyright stuff: https://github.com/chanind/hanzi-writer/pull/16. Is this the correct way to do this stuff? I copied the APL folder from Make Me a Hanzi, but I didn't know what to do with the other info so I put it into a COPYING.md file trying to mimic what you did in the Make Me a Hanzi repo. Is this the correct way to do this?

Thanks for the amazing work with Make Me a Hanzi!
