### ISSUE TITLE
是否可以增加暫停功能呢 ?

### ISSUE THREAD

**Issue by silent717120** [chanind/hanzi-writer#155]
開發者你好

目前播放中需要有暫停的功能
但 API 裡面似乎沒有看到 stop 和 pause 

之後是否會新增呢 ?

或是要自己新增此功能
建議修改哪些 js 呢 ?

謝謝 !

**Comment by chanind** [comment]
Currently there's not a way to pause and resume animations, but it should be easy to add. I'll try to get a PR up with that functionality soon!

**Comment by silent717120** [comment]
非常感謝你 !!

**Comment by silent717120** [comment]
Thank you very much indeed !!

You are really a great help !!

**Comment by chanind** [comment]
No problem, thanks for the great feature request!
