### ISSUE TITLE
how to install on local server?

### ISSUE THREAD

**Issue by phoeller** [chanind/hanzi-writer#157]
Hi there,
  I am trying to copy and paste the code to use locally. I paste all the source code of hanzi-writer.js to within the script tag, and write a div block such as 

<head>
<script type="text/javascript">
/* I paste all the code of hanzi-writr.js here */
/* then show the character */

var writer = HanziWriter.create('character-target-div', '我', {
  width: 100,
  height: 100,
  padding: 5
});
 </script>
</head>
<body>
<div id="character-target-div"></div>
</body>

I save the whole code as test.html and run it by chrome or edge locally, but it doesn't show me anything. I then copy the code to my private Wordpress blog, still no help. In the local run in edge, when debug in a development tool, it shows me an error

0: Unable to get property 'nodeName' of undefined or null reference

which lead me to 

var nodeType = elm.nodeName.toUpperCase();
  if (nodeType === 'SVG' || nodeType === 'G') {
    svg = elm;
  } else {
    svg = createElm('svg');
    elm.appendChild(svg);
  }

Any idea how to get it installed? By the way, in the instruction page, it is said that I need the library for Chinese characters, I am going to install this in the intranet for internal use purposes so my students could use it. But the intranet is not connecting to internet, so what should I do to install the library properly? Thanks.

**Comment by chanind** [comment]
Ah that looks like it can't find an element on your page with id of `'character-target-div'`, so you would need to make an element that matches like `<div id="character-target-div"></div>` for it to render into. It sounds like it needs a better error message 😅.

If you need to have it work on your intranet, you'll need to host the character data yourself so it's available on the intranet. The data is all at https://github.com/chanind/hanzi-writer-data. You can download all the characters in the `data` folder there, then load them via javascript. There's some more detail on how to do that here: https://hanziwriter.org/docs.html#loading-character-data-link.

**Comment by phoeller** [comment]
Thanks. I fixed the first problem and I am able to show the character when my script linking to the external hanzi-writer-data. But I am still having a hard time to install the hanzi-writer-data to the local intranet. I download all the json and place them to a place that my local server install (says http://192.168.100.2/data) if I access the json with http://192.168.100.2/data/中.json, I see it open the json as HTML content. But when I run it with the javascript , I got the following error

SEC7120: [CORS] The origin 'file://' did not find 'file://' in the Access-Control-Allow-Origin response header for cross-origin  resource at 'http://192.168.100.2/data/中.json'.

**Comment by chanind** [comment]
hrm cors is header you need to enable on your server. By default the browser won't allow you to load data from a different domain than the domain your site is one without the CORS header turned on. Ex if your site is `www.my-site.com/chinese`, then it would only have access to stuff at the `www.my-site.com/*` urls. One thing you could do is put the data files in the same place as your web page, so if your web page is, for example, `www.my-site.com`, then you could try putting the data at `www.my-site.com/hanzi-writer/data/中.json`. Then you shouldn't have any CORS issues.

**Comment by phoeller** [comment]
Thanks chanind. I may need sometimes to figure out how it works. I don't have IT in my local school yet. And the webpage I am setting on is actually a blog and we create one post for one practice for the students. Each post seems to have its own location on the server and I must put them in a common location so each post could access the data. But as what you said, I think I put data on the same domain (they are all in 192.168.100.2/data, however, the post are in something like 192.168.100.2/posts/xxxx/xx, may be that is the problem?

**Comment by chanind** [comment]
hrm it shouldn't be a CORS issue then.. What code are you using for `charDataLoader` in Hanziwriter?

**Comment by phoeller** [comment]
> hrm it shouldn't be a CORS issue then.. What code are you using for `charDataLoader` in Hanziwriter?

I copy and paste the code of https://cdn.jsdelivr.net/npm/hanzi-writer/dist/hanzi-writer.min.js, and I just modify the address pointing to the data file. I also try https://cdn.jsdelivr.net/npm/hanzi-writer/dist/hanzi-writer.js, the same result.

**Comment by chanind** [comment]
I'm not sure how CORS works when you're loading directly from a local IP address. What's the URL of your page it's loading from? Is it also `http://192.168.100.2/X`? It might help if you set up a DNS record for 192.168.100.2 so that you can load, for example `http://hanzi-internal.com/X` instead of `http://192.160.100.2`. Still, I'm surprised it's giving CORS issues...

**Comment by phoeller** [comment]
Hi there, thanks for your reply. I just figure what is going on. It seems that the data files are too big to upload at once so cause corruption. I re-upload them, now good.

**Comment by chanind** [comment]
Ah glad to hear it! Good luck!
