### ISSUE TITLE
writing sequences

### ISSUE THREAD

**Issue by HelloRickey** [chanind/hanzi-writer#158]
Hello, I need to develop a function now. Input Chinese characters to get the stroke order coordinates of this Chinese character. For example, input "十". It is composed of horizontal (一) and vertical (｜). The start coordinate of horizontal (一) is (0, 5) end coordinate (10, 5), and the start coordinate of vertical (｜) (5, 0) end coordinate (5, 10),  How to use Hanzi writer to get the coordinates of these writing sequences？

**Comment by chanind** [comment]
For your case, you probably don't need to use the HanziWriter library - you can just use the JSON data for each character. All the data is at: https://github.com/chanind/hanzi-writer-data. For instance, the data for 中 is at: [https://github.com/chanind/hanzi-writer-data/blob/master/data/中.json](https://github.com/chanind/hanzi-writer-data/blob/master/data/%E4%B8%AD.json). You probably just need the `medians` array from the data, which draws a line along the center of each stroke. So, the first point in `medians` for each stroke is what you'd be looking for. the only tricky thing is that the points coordinates vary from `x` between `0` and `1024`, and `y` between `900` and `-124`, so you'll need to do some math to transform the coordinates into whatever grid you're using.

**Comment by HelloRickey** [comment]
Thank you
