### ISSUE TITLE
Adding width and height to character dynamically 

### ISSUE THREAD

**Issue by infinyte7** [chanind/hanzi-writer#166]
According to dimensions of screen size how can I add width and height dynamically to HanziWriter character.
For id="grid-background-target"
Using width=100% height=100%
Characters is not get resized.
Working but for characters, what should be the option?

**Comment by SimondNew** [comment]
how did you resolve this problem

**Comment by infinyte7** [comment]
View this
https://github.com/infinyte7/Anki-xiehanzi/blob/master/Versions/Version%201.7/back.html#L684-L709

I have used it my project.
