### ISSUE TITLE
怎么在实例创建之后去设置更新播放速度呢？

### ISSUE THREAD

**Issue by SimondNew** [chanind/hanzi-writer#182]
当我使用_init时，播放速度可以改变，但是他会自动生成一个新的svg，导致我的页面出现两个svg。
如何正确的更新播放速度呢，在文档里没有看到说明

**Comment by chanind** [comment]
There's not a good way to do that currently, but for animation speed it shouldn't be hard to add. I'll work on a PR to address that. In the meantime, it's hacky, but you can probably just directly override the options directly with something like: `writer._options.strokeAnimationSpeed = 2.5`. I think this will only work for the unminified JS, but I could be wrong.

**Comment by SimondNew** [comment]
Thank you , i override the options directly and it resolves my problem.
