### ISSUE TITLE
Loading data from Hanzi Writer CDN via 'https'

### ISSUE THREAD

**Issue by TimAstier** [chanind/hanzi-writer#19]
Hello there. Thanks a lot for building this amazing library!

I'm trying to use hanzi-writter on an app hosted on heroku.
Everything works well in development but in production I get the following error:

Mixed Content: The page at [...] was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://chanind.github.io/hanzi-writer/cdn/2/data/%E6%B3%95.json'. This request has been blocked; the content must be served over HTTPS.

Is there any way to change the defaultLoader to 'https'?
(I'm not sure this is a good idea, I'm rather new to development).

Alternatively, is there any way to pass the JSON data directly to new HanziWriter instead of passing a custom closure to the charDataLoader option? (the data would already be fetched in advance and there is no need to do a new network call).

Thanks!

**Comment by TimAstier** [comment]
Just realised I can ''hardcode the data for that character'' as mentioned in the docs.

**Comment by chanind** [comment]
Ack really sorry I didn't realize it was loading over http! I'll change the default to https - that's the right call in all situations. I'll fix and make another release. Thanks for flagging!

**Comment by chanind** [comment]
Release 0.2.1 fixes this issue. If you update your version on HanziWriter it should work with https now.

**Comment by TimAstier** [comment]
Great! Thanks a lot! That way I don't have to manually import the data for every character :))
