### ISSUE TITLE
Demo not working because it is linking to a non-existent js file

### ISSUE THREAD

**Issue by junjie** [chanind/hanzi-writer#201]
The demo (demo/index.html) is not working because it is linking to a non-existent js file:

https://github.com/chanind/hanzi-writer/blob/3ebc504e4d694ee50208f763e4079101524f73b9/demo/index.html#L32

I'm new to this project and may be missing something. But if this is something you guys are unaware of and would be open to fixing, I can open a pull request to fix this by replacing that with the link to the CDN.

**Comment by chanind** [comment]
The demo requires you to build the build the JS locally first with `yarn build`. It's more there as an easy way to test changes locally in the browser.

**Comment by junjie** [comment]
Got it, thanks! Great project btw
