### ISSUE TITLE
 from origin 'null' has been blocked by CORS policy:

### ISSUE THREAD

**Issue by Qdafengzi** [chanind/hanzi-writer#202]
```javascript
var writer = HanziWriter.create('target', '我', {
  charDataLoader: function(char, onComplete) {
    $.getJSON("/data/" + char + ".json", function(charData) {
      onComplete(charData);
    });
  }
});
```

I want use it in Android but  load local data error:

 index.html:1 Access to XMLHttpRequest at 'file:///xxxx/hanzi/data/%E4%B8%96.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

**Comment by chanind** [comment]
Sorry for the slow reply. This seems like more of a question about how to load a local json file in an Android webview. I don't have a lot of experience with Android webviews, but you can try googling about it. Maybe something like this? https://stackoverflow.com/questions/20425481/android-webview-ajax-local-files

**Comment by Qdafengzi** [comment]
> Sorry for the slow reply. This seems like more of a question about how to load a local json file in an Android webview. I don't have a lot of experience with Android webviews, but you can try googling about it. Maybe something like this? https://stackoverflow.com/questions/20425481/android-webview-ajax-local-files

I have make it ，thank you
