### ISSUE TITLE
How to import to React project?

### ISSUE THREAD

**Issue by niustem** [chanind/hanzi-writer#209]
I use create-react-app. in package.json, I installed these two dependency, but import failed...
"hanzi-writer": "^2.3.0",
"hanzi-writer-data": "^2.0.1",
![无标题](https://user-images.githubusercontent.com/5278653/104116387-0b2fb900-5353-11eb-880e-c1ecc0cc2df0.png)

**Comment by chanind** [comment]
This is just typescript saying that there's no type definitions file for Hanzi Writer. You can just disable that warning and it should be fine. Depending on how your module imports are set up, you might need to do `import HanziWriter from 'hanzi-writer'`, or `import * as HanziWriter from 'hanzi-writer'`

**Comment by niustem** [comment]
you are right, Thank you so much.  ^_^
It is another problem, I fixed after I get help from you.
![无标题](https://user-images.githubusercontent.com/5278653/104180472-203a4400-5448-11eb-9a62-cd6a73885b3b.png)
