### ISSUE TITLE
svg can't get the correct clip-path if url contains ')' or '('

### ISSUE THREAD

**Issue by cqiangcode** [chanind/hanzi-writer#215]
et: <path clip-path="url(https://xxx.com?keyword=(1)#mask-145)

**Comment by chanind** [comment]
great find! Probably need to do better escaping on the clip path to address this.

**Comment by cqiangcode** [comment]
> great find! Probably need to do better escaping on the clip path to address this.

maybe use cli-path style like 'clip-path: path('M 0 200 L 0,75 A 5,5 0,0,1 150,75 L 200 200 z');' is a better choice?
