### ISSUE TITLE
vue import HanziWriter from 'hanzi-writer';   report errors

### ISSUE THREAD

**Issue by lixue128** [chanind/hanzi-writer#220]
![077CBE26-1035-4D88-96DC-69C5F18781F3](https://user-images.githubusercontent.com/37533339/108988058-faeb5780-76ce-11eb-826b-831a48706cf5.png)

**Comment by lixue128** [comment]
node version 14.15.3

**Comment by chanind** [comment]
Hopefully this should be fixed in 3.0.3. Let me know if it still has issues!
