### ISSUE TITLE
Desktop-based version?

### ISSUE THREAD

**Issue by baimafeima** [chanind/hanzi-writer#23]
Can hanzi-writer be used as a standalone desktop-based software on Linux-based operating systems? If not, would you consider modifying it so that it can be used on the desktop? I wouldn't know how to use it otherwise.

**Comment by chanind** [comment]
Hanzi-writer is just a javascript library, so it should be possible to develop a desktop application that uses it. It's not uncommon to develop desktop applications now using web technologies, for example using Electron (https://electronjs.org). Does this answer your question, or am I misunderstanding?

**Comment by baimafeima** [comment]
Thanks a lot for the clarification. Would you consider making a desktop application in the foreseeable future?

**Comment by chanind** [comment]
I don't plan on building any applications for Hanzi-writer - I'm just focused on making the library itself better. Other developers can take Hanzi-writer and make desktop or other applications with it. It's all free and open source so I hope others will take it and build innovative applications for Chinese learning.

**Comment by chanind** [comment]
Closing for now. If you or anyone else wants to make a desktop application using Hanzi writer feel free open an issue with any questions you may have!
