### ISSUE TITLE
How make a new hanzi-write-data?

### ISSUE THREAD

**Issue by ShawnSen** [chanind/hanzi-writer#232]
If the hanzi-write-data is no hanzi that I need,how can I make a new hanzi-write-data?Like 籸(shen) ,it's my name.

**Comment by AntonOfTheWoods** [comment]
Could you try combining the parts of two other characters? Like 粉.json and 讯.json? It may also be necessary to tweak the widths so the components are positioned correctly. That might be a pain.

**Comment by ShawnSen** [comment]
> Could you try combining the parts of two other characters? Like 粉.json and 讯.json? It may also be necessary to tweak the widths so the components are positioned correctly. That might be a pain.
> 
> It would actually be pretty awesome to have a "community-contributed" extra repo that could house new characters such as this. Or even just keep augmenting the main data store.

**Comment by rdrg109** [comment]
@AntonOfTheWoods I support your idea. If such project existed, please let me know, I'd be eager to contribute.
