### ISSUE TITLE
Is this still available to WeChat mini program?

### ISSUE THREAD

**Issue by Irene97-bit** [chanind/hanzi-writer#233]
Hi, I tried the demo several times in WeChat mini program, but the character always failed to be rendered and displayed, without  any accountable solutions. Anyone could help me? Thanks million.

**Comment by passion2win** [comment]
he reason is Wechat basic library. If the library is under 2.7.7, now the version 1.1.0 of hanzi-writer-miniprogram works, or it doesn't work.

**Comment by Irene97-bit** [comment]
Thank you very much! It works!
