### ISSUE TITLE
Totally offline hanzi-writer

### ISSUE THREAD

**Issue by BlindB0** [chanind/hanzi-writer#288]
Is the any way to make hanzi-writer totally offline?
So, no https://cdn.jsdelivr.net/npm/hanzi-writer-data@2.0 at all, just read local JSON files in the same folder as hanzi-writer.html (with  hanzi-writer script in it).
Local webserver with JSON delivery also not possible.
I try to make offline Anki deck (on android Ankidroid too) with hanzi-writer in it.

**Comment by chanind** [comment]
That should be possible. You just need to overwrite the `charDataLoader` option to return the character data, however you decide to store it. Basically if you can write a function in JS that takes in a character string and returns the JSON data for that character then you're good to go. More details on the `charDataLoader` option here: https://hanziwriter.org/docs.html#loading-character-data-link

**Comment by DzSom02** [comment]
@BlindB0 Did you manage to make it work in AnkiDroid? I'm trying the same also and for whatever reason is not shown in AnkiDroid

**Comment by BlindB0** [comment]
Hi @DzSom02 !
Yes, I can do it. AnkiDroid works totally offline with hanzi-writer.
I can share my deck, so you can see  how I made it.

**Comment by DzSom02** [comment]
@BlindB0 Yes! I think that would be very appreciated! Thank you!

**Comment by BlindB0** [comment]
https://file.io/bP6VsfOQWPvW
Here my deck for hanzi. Archive inside you should unpack to anki media folder. I made it in desktop version and than sync it with ankidroid. But you can unpack it to ankidroid media folder on android phone.
Check js code in cards for better understanding.

**Comment by vherrmann** [comment]
The deck https://github.com/krmanik/Anki-xiehanzi/ or  can be used as a reference as well.

**Comment by vherrmann** [comment]
Also, @BlindB0 should close this issue, since your problem has been solved.
