### ISSUE TITLE
quiz mode: if I made a mistake 2 times, I'd like the stroke to be drawn for me

### ISSUE THREAD

**Issue by ganqqwerty** [chanind/hanzi-writer#289]
I see that I have access to the writer object from onMistake callback. However, I did not understand if it's possible to command the writer to count my mistake as non-mistake and draw the stroke properly. 

The problem that I'm solving is this: some strokes are hard to get right, so the user spends a lot of time trying to be precise, drawing the stroke again and again. I counted that it takes 1.5 - 3 times more to draw a kanji using this strategy than when the stroke is autodrawn after a couple of attempts. When we talk about 100 reviews a day, this is a difference between 20 min of study and a full hour, every day.

**Comment by chanind** [comment]
This sounds like a great feature request! I can see how this would be useful. If I understand correctly, you'd like a setting for quizzes where you could say something like: `writer.quiz({ markStrokeCorrectAfterAttempts: 2 });`?

**Comment by ganqqwerty** [comment]
yes, something like that would be great

**Comment by chanind** [comment]
I also wonder if this is a sign that the stroke grading for some strokes is too strict or could be improved. Are there any particular characters or stroke types you see this happen on?

**Comment by ganqqwerty** [comment]
> I also wonder if this is a sign that the stroke grading for some strokes is too strict or could be improved. Are there any particular characters or stroke types you see this happen on?

I would list two types of strokes that: 
* long vertical stroke, like in 十
* medium-small dots like in 禾, 父
