### ISSUE TITLE
Thanks from Wikimedia !

### ISSUE THREAD

**Issue by hugolpz** [chanind/hanzi-writer#30]
Hi there, we from the Wikimedia Commons Stroke Order project are discovering your Hanzi-Writer and MakemeaHanzi projects. These 2 projects are awesome, more powerful than our graphic-designers-centered approach, and I'am so impressed by your both project. Thanks a lot for sharing them under MIT License, it's a blessing for the global community and cross-cultural understanding :+1: :100: 
Thanks!

**Comment by chanind** [comment]
Thank you for the kind words, Hugo! I'm really excited to hear you're finding Hanzi-Writer useful over at Wikimedia! The commons stroke order project is an awesome undertaking! Most of the credit belongs to @skishore for creating MakemeaHanzi. Thanks to him extracting stroke and rendering data for each character and making it open source, building a JS library like Hanzi-writer is easy :)

**Comment by hugolpz** [comment]
I'am also contacting @skishore, his project's UI and use of Arphic Ukai is smart :dancer: 
I will work to integrate the data of Skishore as images within Commons SO project, but I will also raise awareness about your hanzi-writer js libs. Very cool. And the quizz functionality is the holy grail of Characters e-learning. :dancer:

**Comment by hugolpz** [comment]
Ok ! I think we can close this issue.
- [x] Thanks + Hello :ballot_box_with_check: 
I will spread the word in my community|ies, Wikimedia and [academics](tclt.us/tclt10/).
