### ISSUE TITLE
code improvement proposal for API of loadCharacter

### ISSUE THREAD

**Issue by vaab** [chanind/hanzi-writer#41]
The default loading process allows to use either a promise function or a direct function for the implementation of option ``charDataLoader`` function (and as I understand it):

```
HanziWriter.prototype._loadCharacterData = function(char) {
  if (this.isLoadingCharData) this.cancelLoadingCharData();
  this.isLoadingCharData = true;
  return new Promise((resolve, reject) => {
    this.cancelLoadingCharData = reject;
    const returnedData = this._options.charDataLoader(char, resolve);
    if (returnedData) resolve(returnedData);
  }).then((data) => {
    this.isLoadingCharData = false;
    return data;
  });
};
```

why not directly force only one usage (the use of promises) for the sake of clarity and avoid having to provide resolve/onSuccess and reject/onFailure (that last one being not implemented for now) as arguments.

Most of the time, if you choose not to load ALL the ~100Mb of the database in RAM, a loader will be forced to wait for disk I/O and as such seem to be a normal candidate for promises, and even if it is not the case, we could have animation or other lightweight threads underway that would be probably happy to have the opportunity to do some processing at that point without hurting the loading process. 

To be clearer, I would suggest to call loadCharacter directly as:
```
this._options.charDataLoader(char).then(...onSuccessCallable..., ...onFailureCallable...)
```
And remove the intermediate function ``_loadCharacterData``.

I'm willing to provide you a PR with the modification that this implies, but I want to make sure that makes sense for you before heading forward.

Many thanks for you library !

**Comment by vaab** [comment]
There is a second issue on the implementation of the current ``HanziWriter.prototype._loadCharacterData`` as I understand it : by keeping the ``reject`` of the promise, you'll trigger any error from a loading, only on the next time you'll be loading the char (because you trigger the last ``reject`` on the beginning of the function). Of course, this is possible if the user-provided ``charDataLoader`` actually do not call the ``resolve()``.

All this is not crystal clear for me yet, so please accept my apologies if there's anything I got wrong.

**Comment by chanind** [comment]
It would be cleaner to only use promises, but I was worried that some developers, especially new developers, don't really understand how promises work and might be confused. The way it's written now you can return a promise if you want, or use the callback, whichever you think is easier. Changing to promise-only would be a breaking change so would require some time to deprecate it so everyone can migrate.

Currently if the loading fails Hanzi Writer will just hang and not do anything, but thinking more it probably makes sense to provide `onLoadSuccess` and `onLoadFailure` callbacks or something like that so developers can show a spinner if they want. I don't think there's any harm in passing the `reject` callback to the `charDataLoader` function - I'll test a bit more later just to be sure. The most direct option to fail loading currently is to throw an exception in `charDataLoader`, as that will also reject the promise.

**Comment by vaab** [comment]
Your explanation about not using promises seems sound enough to keep the current API for me. 

And please, be sure to check my PR #42 (which should be the answer to everything)  before attempting anything on your end especially if it is trying to add an ``.onLoadFailure(...)`` as I already implemented something following this idea that you might want to check before.

**Comment by chanind** [comment]
Closing as #42 is now merged.

**Comment by vaab** [comment]
Thanks the final solution is more than satisfying !
