### ISSUE TITLE
Chinese MOOC's hanzi-writer based activity live !

### ISSUE THREAD

**Issue by hugolpz** [chanind/hanzi-writer#45]
Hi there,
Just to let you know, a service will be published tomorrow thanks to your library.
I downloaded your last min.js from your website, but drawingWidth works. As do rads.

Prod : https://hanzi.cri-paris.org/#L2%E5%9B%BD
Credit : see footer :+1: Thanks !
Public : ~8000 Chinese learners in Francophonia :D
Project: #MOOCdeChinois #free .
Publication: 2018/02/05
Licence : MOOCdeChinois is CC-by-sa-nc . I push for OpenSource. My code is MIT.

![index](https://user-images.githubusercontent.com/1420189/36256330-c21b0650-1252-11e8-9adc-c28e280ecef4.png)

![screenshot from 2018-02-12 00-19-42](https://user-images.githubusercontent.com/1420189/36256316-b4a78a8e-1252-11e8-8713-af96f7ed8045.png)

![screenshot from 2018-02-12 00-51-59](https://user-images.githubusercontent.com/1420189/36256492-8956caa6-1253-11e8-803b-36699f6cacec.png)
![screenshot_20180215-091733](https://user-images.githubusercontent.com/1420189/36257026-a25a657e-1255-11e8-8d23-fb3065548396.png)

I hope to redirect to you a hand of good willed JS devs :1st_place_medal: 
Maybe I should redirect them more toward MakeMeHanzi / CJKanimate where more work is needed ?

**Comment by chanind** [comment]
Thanks @hugolpz, your demo looks great! Awesome job integrating Hanzi Writer with audio and a great UI!

Any help is always appreciated, and any improvements to MakeMeAHanzi also help too since that's where all the data is from. Thanks so much!

**Comment by hugolpz** [comment]
@skishore

**Comment by hugolpz** [comment]
Apps is live ! See upper for link.
The teaching team didn't fully switched to this app to support their MOOC tho.
They still rely on old Flash animations :sob: 

![screenshot from 2018-02-15 13-16-07](https://user-images.githubusercontent.com/1420189/36256284-8d2cae80-1252-11e8-8dfe-1afce65acdd7.png)

![hanziwriter3](https://user-images.githubusercontent.com/1420189/36256294-96bde9e6-1252-11e8-9d31-9fa0149c3bc9.png)

**Comment by hugolpz** [comment]
Note: The **mid-project report** is [there](https://github.com/hugolpz/OpenEdx-hanzi/issues/15). I barely acted on it since.
The final report is expected in June.
