### ISSUE TITLE
performance and aspect of hide/showing a full character

### ISSUE THREAD

**Issue by vaab** [chanind/hanzi-writer#48]
When hiding/showing a character, it seems that hanzi-writer in actually modifying the opacity of each strokes which draws to concerns:
- when strokes are crossing each others, there's an unpleasant effect as the mixing of 2 layers of opacity is creating a more opaque zone on the crossing section.
- isn't this way to complicated to animate the opacity of all strokes when the opacity of the parent node could be managed once ?

And as mentionned in a comment in #47 , should we think about CSS animations ?

**Comment by chanind** [comment]
That's a really great point - I hadn't thought of having an opacity control on the parent element itself! We can wrap each character layer in a `<g>` element and then tween the opacity of that element when we want to hide / show a whole character. That should get rid of the ugly opacity overlap regions like you said.

As for CSS animations, I think it's definitely worth investigating. The challenge as I see it with CSS animation is that it's harder to have as fine-grained control over when the animation starts and stops, and knowing exactly how far an animation has progressed. It's worth researching more though, it's possible that we can accomplish everything we need to with CSS animation instead. I don't know if the performance would be that different though unless we can get the animation to be hardware accelerated, but I'm not sure of the details.

**Comment by vaab** [comment]
CSS are hardware accelerated: https://www.sitepoint.com/introduction-to-hardware-acceleration-css-animations/

**Comment by chanind** [comment]
CSS animations are only hardware accelerated for a few properties, like `translate` and `opacity` (from the article you shared). I'm also not sure if that applies to SVG. For stroke animations, the property that would need to be accelerated would be `stroke-dashoffset`.

**Comment by chanind** [comment]
fixed by #56
