### ISSUE TITLE
Final flashing color distinct from stroke hint flashing color

### ISSUE THREAD

**Issue by vaab** [chanind/hanzi-writer#49]
The final flashing color should definitively be separated from the hint as visually they represent 2 conflictual visual communication:
- a stroke hint appears when you were wrong after X times... it is a correction. Common colors that could come to mind is redish colors.
- the final victory flash is a confirmation that you are right. People might want to use green or yellow bright colors. But not refer to the colors used when you actually failed.

Does this make sense ? I can work on that in a few days if this seems okay for you.

**Comment by chanind** [comment]
yeah, that definitely makes sense, I think it's worth adding a separate option for the final victory color. They're just the same right now because they both use the same character layer, but there's no reason why we can't set a different color immediately before flashing at the end.

**Comment by vaab** [comment]
I tried to follow your suggestion of setting the color just before flashing. I hope this helps.
