### ISSUE TITLE
Provide parameter for margin

### ISSUE THREAD

**Issue by hugolpz** [chanind/hanzi-writer#58]
The margin between the character's bounding box and the svg bounding box is too large and impose too much dead space. Ex : 
* svg element set as : 300x300px
* character bounding box : 192x227px
* approx default margin observed: 35 54 35 54px; (10% and up on each side)

Provide a parametter to control this margin or translate would be helpful. :+1: 

![hanziwriter1](https://user-images.githubusercontent.com/1420189/36255948-39a21404-1251-11e8-9b72-43f8a5bd5db0.png)
![hanziwriter2](https://user-images.githubusercontent.com/1420189/36255947-397f8dee-1251-11e8-9f25-32dffba6807f.png)

For reference, on Wikimedia Commons and for similar 300x300, we used 15px margins (5% and up) on each side.

**Comment by chanind** [comment]
There's a parameter called "padding" that controls this. If you set it to 0
it should make the character full size.

**Comment by hugolpz** [comment]
Ok thanks. Great.
Please document it as well. Cheer !

**Comment by chanind** [comment]
👍 I think for the next major release it probably makes sense to set this to 0 by default. The 20px padding currently wasn't a good default.

**Comment by hugolpz** [comment]
Not sure. Depending on how your padding works.
The padding-top and padding-bottom (the smallest ones) I observe visually varies. See top of
- [#中](https://hanzi.cri-paris.org/#S2%E4%B8%AD) 
- [#S2国 ](https://hanzi.cri-paris.org/#S2%E5%9B%BD).

Also, I wonder how they will behave if padding: 0.

**Comment by hugolpz** [comment]
Edit note: in my initial screenshots previously discussed, padding was already set to `5`.
Below, I will focus on `padding: default`, and `padding: 0` to illustrate the rendering.

## Rendering with padding no defined = default
![hanzi-padding-default-g_element](https://user-images.githubusercontent.com/1420189/36424827-019b51c2-1645-11e8-9caf-9470bc3f2cf5.png) ![hanzi-padding-default-svg](https://user-images.githubusercontent.com/1420189/36424829-01b32bd0-1645-11e8-80dc-693d5544d608.png)

## Rendering with padding = 0
![hanzi-padding-0-g_element](https://user-images.githubusercontent.com/1420189/36424837-0bf3e1d4-1645-11e8-9688-9094ce050ba8.png) ![hanzi-padding-0-svg](https://user-images.githubusercontent.com/1420189/36424838-0c097d64-1645-11e8-95f6-2338b27369d9.png)

![hanzi-padding-0-g_element-zhong](https://user-images.githubusercontent.com/1420189/36424942-6606fc92-1645-11e8-9b2c-581b4bcba660.png) ![hanzi-padding-0-svg-zhong](https://user-images.githubusercontent.com/1420189/36424945-662b4ef8-1645-11e8-9c70-9bdcfc0e33c3.png)

### Recommendation
1. Indeed, default should be `padding: 0`.
2. Maybe even smaller.
3. There are hidden difficulties due to the irregular height of Chinese characters, as you know.
