### ISSUE TITLE
drawnPath not working on some devices

### ISSUE THREAD

**Issue by hugolpz** [chanind/hanzi-writer#67]
As I collect data, some users don't return drawnPath's data.
Quite marginal. Need one more week.

![screenshot from 2018-02-26 15-31-53](https://user-images.githubusercontent.com/1420189/36675757-2fe7be70-1b0a-11e8-99d5-d70c9e6a65be.png)

Need cross platform / browsers / UI tests.

**Comment by chanind** [comment]
That's troubling. Do you know which browser those users are using?

**Comment by hugolpz** [comment]
I haven't implemented browser / devices detection yet. But they seems to be able to proceed properly for stroke practice. Do you use a touch event and not a click event? It could exclude mouse.

**Comment by hugolpz** [comment]
https://github.com/hugolpz/OpenEdx-hanzi/issues/12 -- done

Waiting user data.

**Comment by hugolpz** [comment]
Nothing in past 1000 strokes or 10~30 users.

I start to think this "Paul" just never close his tabs and was using an older, cached version of my main.js , and i reacted too quickly. If no other occurence in next day or two, we can close this issue.

**Comment by hugolpz** [comment]
After examination of the last 2000 queries with no missing data, I'am confident this bug was a false positive. :arrow_right: Close.

**Comment by chanind** [comment]
phew, glad to hear it!

**Comment by hugolpz** [comment]
I'am checking out this app almost every 2 hours, a bit over reacting.
I will buffer better in future. :+1:
