### ISSUE TITLE
Single touch counted as mistakesOnStroke

### ISSUE THREAD

**Issue by hugolpz** [chanind/hanzi-writer#69]
> Simply for awareness. Based on my app and my custom made data collection.

Single touch/click fire a `mistakesOnStroke`, returns the flash hint of the correct stroke to draw next. Behavior as expected, but doesn't seems to be a real writing attempt. Maybe the user : 
- do an unwanted click
- use it a click to get the hint

Asking myself as a app dev : should I filter this out ? Should it be counted as a mistakesOnStroke? :thinking: 

![screenshot from 2018-02-28 17-48-32](https://user-images.githubusercontent.com/1420189/36800405-c3546996-1caf-11e8-943f-513b20230e26.png)

**Comment by chanind** [comment]
That's a good observation. We should just ignore single-point strokes

**Comment by hugolpz** [comment]
Please also note there are some "double click" it seems. Which don't make much sense as well. But overall, it seems that some users's systems (OS+browser+mouse) are just sending back more datapoints and others less datapoints. See :arrow_down: 

![screenshot from 2018-03-01 11-57-05](https://user-images.githubusercontent.com/1420189/36841167-c1554dd4-1d47-11e8-9a33-6bf12bb467a4.png)
