### ISSUE TITLE
Loop characters sequentially

### ISSUE THREAD

**Issue by donnekgit** [chanind/hanzi-writer#82]
First of all, thanks so much for this resource!

I'm trying to get an effect as on the first page of the website, where each character is animated automatically (ie you don't need to press a button), but the animation for that character doesn't begin again until all the characters in the sequence have finished animating - just like the chained animation in the docs, but not requiring a button-press.

I've adjusted the looping code in the docs as follows:
```
<div class="inline-demo-flex">
    <div id="docs-target-5-1" class="inline-demo"></div>
    <div id="docs-target-5-2" class="inline-demo"></div>
</div>
<script>
(function() {
    var char1 = new HanziWriter('docs-target-5-1', '很', {
    width: 100,
    height: 100,
    padding: 5,
    delayBetweenStrokes: 100, // milliseconds
    delayBetweenLoops: 5000
    });
    
    var char2 = new HanziWriter('docs-target-5-2', '好', {
    width: 100,
    height: 100,
    padding: 5,
    delayBetweenStrokes: 100, // milliseconds
    delayBetweenLoops: 5000
    });

    char1.loopCharacterAnimation();
    char2.loopCharacterAnimation();
    
})();
</script>
```
But this just leaves the two characters looping independently.  Is there any way to get them looping sequentially?  Thanks.

**Comment by chanind** [comment]
You can get them to loop sequentially by using the `onComplete` callback like in the [chaining animations doc](https://chanind.github.io/hanzi-writer/docs.html#chaining-animation-link), but the trick is to call the function again from the start when the second character finishes animating. Here's an example, modifying the code from the docs:

```javascript
var char1 = new HanziWriter('character-target-1', '很', {
  width: 100,
  height: 100,
  padding: 5,
  showCharacter: false
});
var char2 = new HanziWriter('character-target-2', '爽', {
  width: 100,
  height: 100,
  padding: 5,
  showCharacter: false
});

function chainAnimationsForever() {
  var delayBetweenAnimations = 1000; // milliseconds
  char1.hideCharacter();
  char2.hideCharacter();

  char1.animateCharacter({
    onComplete: function() {
      setTimeout(function() {
        char2.animateCharacter({
          // add a second onComplete here, and call the outer chainAnimationsForever() again
          onComplete: function() {
            setTimeout(chainAnimationsForever, delayBetweenAnimations);
          }
        });
      }, delayBetweenAnimations);
    }
  });
}

// start the chain!
chainAnimationsForever();
```

**Comment by donnekgit** [comment]
Cool - that works great.  Thanks so much!

**Comment by Destaq** [comment]
What if you don't know the number of characters that there will be? This won't work for *n* unknown characters...
