### ISSUE TITLE
Translate docs into Chinese

### ISSUE THREAD

**Issue by chanind** [chanind/hanzi-writer#89]
Currently the website and docs are all in English.

If you'd like to help with this, you can check out the site in the `gh-pages` branch. You can run the site locally with `jekyll serve`. (you'll need to run `bundle install` first)

**Comment by 17625693** [comment]
writer.updateColor('strokeColor', '#AA12CD');

code：
HanziWriter.prototype.updateColor = function (colorName, colorVal) {
          var _this7 = this;

          var options = arguments.length > 2 && arguments[2] !== undefined ? arguments[2] : {};

          return this._withData(function () {
            var duration = typeof options.duration === 'number' ? options.duration : _this7._options.strokeFadeDuration;
            var fixedColorVal = colorVal;
            // If we're removing radical color, tween it to the stroke color
            if (colorName === '**radicalColor**' && !colorVal) {
              fixedColorVal = _this7._options.strokeColor;
            }
            var mappedColor = colorStringToVals(fixedColorVal);
            _this7._options[colorName] = colorVal;
            var mutation = characterActions.updateColor(colorName, mappedColor, duration);
            // make sure to set radicalColor back to null after the transition finishes if val == null
            if (colorName === '**radicalColor**' && !colorVal) {
              mutation = mutation.concat(characterActions.updateColor(colorName, null, 0));
            }
            return _this7._renderState.run(mutation).then(function (res) {
              return callIfExists(options.onComplete, res);
            });
          });
        };

**Comment by chanind** [comment]
Added by @JunaYa! Thanks @JunaYa!!
