### ISSUE TITLE
Touch stroke not recognised same as click stroke

### ISSUE THREAD

**Issue by TomClarkson** [chanind/hanzi-writer#9]
Hanzi-writer looks awesome :) I'll probably use for a Japanese app I'm building https://www.kickstarter.com/projects/265123070/jlpt-gold

I've tested the writing quiz on android and ios and it doesn't seem to capture the touch and move correctly. I've reproduced it here https://youtu.be/i5e9pP_xaeo

I see HanziWriter is listening to touch events but I'm not sure why it isn't working. After the kickstarter campaign I should have more time to look into it.

Thanks!

**Comment by TomClarkson** [comment]
Hmm seems to work with the demo from this repository, just tested it locally and it works and uploaded here http://last-band.surge.sh/

**Comment by chanind** [comment]
Oops, thanks for finding this and apologies for the delay responding! It should be fixed now by: https://github.com/chanind/hanzi-writer/commit/b74b364fbcf2b3a07e54cbf0a58bb747718dbdcf
