### ISSUE TITLE
Issue with leniency in short parallel strokes

### ISSUE THREAD

**Issue by peterolson** [chanind/hanzi-writer#90]
In `strokeMatches.js`, there's this logic starting on line 113

```
// if there is a better match among strokes the user hasn't drawn yet, the user probably drew the wrong stroke
const laterStrokes = character.strokes.slice(strokeNum + 1);
for (let i = 0; i < laterStrokes.length; i++) {
  const laterMatchData = getMatchData(points, laterStrokes[i], options);
  if (laterMatchData.isMatch && laterMatchData.avgDist < strokeMatchData.avgDist) return false;
}
```

This makes perfect sense, but if I have a quiz with higher lenience, it makes it uncharacteristically strict for some characters which have two similar strokes in close proximity to each other, like 月 and 是. 

Let's say you have two short horizontal strokes right next to each other: if you draw the first one slightly too far down, it will think you drew the "wrong" stroke because it was closer to the second short horizontal stroke.

Can we have a way to disable this "future stroke" detection? Or perhaps there's a more elegant way to handle this use case.

**Comment by chanind** [comment]
That's a good point. I think it should be possible to add some extra logic
to handle this case, maybe make it more lenient in cases that match what
you described. One possibility would be to add a penalty to the match score
if another stroke matches closer rather than rejecting the match entirely.
I'll experiment and make a PR (or feel free to do so yourself if you'd
like).

**Comment by chanind** [comment]
Does #92 look like it should solve the issue? I'm not sure about the exact thresholds yet, but I think the idea should be reasonable

**Comment by peterolson** [comment]
Yeah, thanks for taking a look! I'll test it out later to see how well it works

**Comment by peterolson** [comment]
I just downloaded the branch and tried it out a bit. It seems to be solving the issue now -- thanks!
