### ISSUE TITLE
Is it possible to show the character stroke by stoke?

### ISSUE THREAD

**Issue by lengyuan** [chanind/hanzi-writer#91]
For the character animation, is it possible to show the character stroke by stoke? 

For example, when one stroke is done, the animation will be paused, the user needs to click a button to continue to the next stroke.

**Comment by chanind** [comment]
There's not a way to do that currently, but this is a good feature request I think. It should be easy to add an `animateStroke()` method. I'll work on adding that and make a PR.

**Comment by lengyuan** [comment]
Thanks for your quick reply. One more thing, is it possible to detect the end of each stroke?

**Comment by chanind** [comment]
Currently there's not a way to do that either, but I think that's a reasonable feature request as well

**Comment by chanind** [comment]
v1.2.0 adds a `writer.animateStroke(strokeNum, options = {})` method which should allow you to animate the character stroke by stroke. This method returns a promise which you can use to know when the stroke animation has finished, or you can pass an `onComplete` callback to `options` when calling this function.
