### ISSUE TITLE
js版本的是永久免费的么

### ISSUE THREAD

**Issue by weikeyan** [chanind/hanzi-writer#97]
https://cdn.jsdelivr.net/npm/hanzi-writer@1.2/dist/hanzi-writer.min.js 这个是永久免费的么？

**Comment by weikeyan** [comment]
请问这个里边用到的字体什么什么字体呢，我们可能要做一个写字游戏需要商业用的，会牵扯到侵权么？这里边用的是什么字体呢

**Comment by chanind** [comment]
I'm not completely sure on all the details of the copyright for the fonts. I'd recommend asking in the [MakeMeAHanzi repo](https://github.com/skishore/makemeahanzi). I think the fonts should be free for most purposes, but I'm not a lawyer 😅
