### ISSUE TITLE
Can't update character

### ISSUE THREAD

**Issue by lolaswift** [chanind/hanzi-writer#99]
I use local installed json data. The first time, the character renders OK.
When I tried to use the instance method:
writer.setCharacter("")
How can I load the new data for the new character?
I've been struggling with getting it work but don't know how. My code is like this:

~~~~
  ngAfterViewInit() {
    this.loadChar();
  }

update () {
  this.loadNewChar();
}

  loadChar() {
    let strArray = this.words[this.i].name.split("");
    let c1 = require(`hanzi-writer-data/${strArray[0]}`);
    this.hw = HanziWriter.create('character-target-div', strArray[0], {
      width: 300,
      height: 300,
      padding: 10,
      radicalColor: '#168F16',
      strokeColor: '#EE00FF',
      showHintAfterMisses: 1,
      highlightColor: '#F75A78',
      charDataLoader: function () {
        return c1;
      }
    });


    this.hw.animateCharacter();

  }

  loadNewChar() {
    let strArray = this.words[this.i].name.split("");
    let c1 = require(`hanzi-writer-data/${strArray[0]}`);
    this.hw.setCharacter(strArray[0]);
  }
~~~~

**Comment by chanind** [comment]
What happens when you call `loadNewChar`? Does it throw an error? Also, how does this get compiled? I'm surprised that calling ```require(`hanzi-writer-data/${strArray[0]}`);``` inside of a function works - usually it's hard to do dynamic requires like that in a browser.

This isn't the root of the problem, but the way the code is written is a bit indirect. I'd recommend the following for the `charDataLoader` option and removing the stuff with `c1`:

```
charDataLoader: function (char) {
    return require(`hanzi-writer-data/${char}`);
}
```
The above assumes it's OK to write `require` inside of a function like you're doing above.

**Comment by lolaswift** [comment]
Thank you so much for your quick help! I've been struggling with the issue for hours :-(.

~~~~
  loadChar() {
    console.log("loadchar");
    let strArray = this.words[this.i].name.split("");
    //this.c1 = require(`hanzi-writer-data/${strArray[0]}`);
    console.log(this.c1);
    this.hw = HanziWriter.create('character-target-div', strArray[0], {
      width: 300,
      height: 300,
      padding: 10,
      radicalColor: '#168F16',
      strokeColor: '#EE00FF',
      showHintAfterMisses: 1,
      highlightColor: '#F75A78',
      charDataLoader: function () {
        return require(`hanzi-writer-data/${strArray[0]}`);
      },
      onLoadCharDataSuccess: function (data) {
        console.log('Success!');
        console.log(data);
      },
      onLoadCharDataError: function (reason) {
        console.log('Oh No! Something went wrong :(');
        console.log(reason)
      }
    });

    this.hw.loopCharacterAnimation();

  }

  loadNewChar() {
    let strArray = this.words[this.i].name.split("");
    //this.c1 = require(`hanzi-writer-data/${strArray[0]}`);
    console.log(strArray[0]);
    this.hw.setCharacter(strArray[0]);
    this.hw.loopCharacterAnimation();
  }
~~~~

The initial render works. animation works, etc. when I call loadNewChar(), I passed in a new char, but it still rended the old char.

**Comment by chanind** [comment]
Could you try the below code? I'm not sure if it will work, but it should add some extra debugging info to help figure out where the issue is.

```
  loadChar() {
    console.log("loadchar");
    let strArray = this.words[this.i].name.split("");
    console.log(this.c1);
    this.hw = HanziWriter.create('character-target-div', strArray[0], {
      width: 300,
      height: 300,
      padding: 10,
      radicalColor: '#168F16',
      strokeColor: '#EE00FF',
      showHintAfterMisses: 1,
      highlightColor: '#F75A78',
      charDataLoader: function (char) {
        console.log('trying to load char', char);
        const loadedData = require(`hanzi-writer-data/${char}`);
        console.log('loaded data', loadedData);
        return loadedData;
      },
      onLoadCharDataSuccess: function (data) {
        console.log('Success!');
        console.log(data);
      },
      onLoadCharDataError: function (reason) {
        console.log('Oh No! Something went wrong :(');
        console.log(reason)
      }
    });

    this.hw.loopCharacterAnimation();

  }

  loadNewChar() {
    let strArray = this.words[this.i].name.split("");
    console.log(strArray[0]); // Confirmed that a new char is generated
    this.hw.setCharacter(strArray[0]);
    this.hw.loopCharacterAnimation();
  }
```

**Comment by lolaswift** [comment]
You just saved my day!! My night still actually.  :-). 5:00am in Amsterdam . I'd like to buy you a beer, at least!!

**Comment by chanind** [comment]
Glad to hear it! What ended up being the issue?

**Comment by lolaswift** [comment]
~~~~
charDataLoader: function (char) {
        console.log('trying to load char', char);
        const loadedData = require(`hanzi-writer-data/${char}`);
        console.log('loaded data', loadedData);
        return loadedData;
      },
~~~~

This function solved the issue. I guess it's the param 'char' should be passed in this function:
charDataLoader: function (char)

I am still a newbie to javascript.

**Comment by lolaswift** [comment]
It's working now but is it safe to do so? What should be the best practice of loading char data when working offline like this?

**Comment by chanind** [comment]
Ah ok, no problem! It depends how your javascript is getting run, but what you're doing is the right idea. I'm still surprised that ```require(`hanzi-writer-data/${char}`);``` works, but since it works then I think it's fine!

If for some reason ```require(`hanzi-writer-data/${char}`);``` didn't work then I'd recommend downloading all the individual JSON files you need from [hanzi-writer-data](https://github.com/chanind/hanzi-writer-data) and loading them however you're able to in the `charDataLoader` function depending on where you app is running (ex node.js vs mobile app webview vs web browser).  If you run into more issues with data loading feel free to post an issue again and we can figure it out!

**Comment by lolaswift** [comment]
Hi Chanind, I really like the library.  Many thanks for sharing it with the world. I'm really grateful for your work and for you help!  In case you have a donation button, I'd like to buy you a drink. Otherwise, please accept my one million thanks :-). Please keep up the great work.

**Comment by chanind** [comment]
I'm glad to hear you like the library! No donations necessary, but thanks for the offer :). Best of luck with your project and let me know if you run into any other issues!
